

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "your-secret-key"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
