services:
  - type: web
    name: django-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    autoDeploy: true
